### ISSUE TITLE
Inward code max length

### ISSUE THREAD

**Issue by ChappersJr** [axlon/laravel-postal-code-validation#13]
Hey,

I've come across a potential issue with the Inward code for a United Kingdom postcode.

From what I've researched the length of the inward code is 3 characters.

Using this example: NN1 5LLL

Even though it's an invalid postcode (inward code being 4 characters long), it gets passed validation.

Resource: https://www.mrs.org.uk/pdf/postcodeformat.pdf

**Comment by axlon** [comment]
Hello @ChappersJr, thank you for your bug report, I just tested this and I think you're right (I'm not from the UK myself so I'm not particularly knowledgable about UK postal codes)

Your example does indeed [match](https://regexr.com/4vbu1), wrapping the pattern does seem to  fix the issue, but I will need to run some tests to make sure nothing else breaks because of this change

**Comment by axlon** [comment]
@ChappersJr please take a look at the change, I think this should fix the issue
