### ISSUE TITLE
Wrong Validation of Irish Eircodes

### ISSUE THREAD

**Issue by taftse** [axlon/laravel-postal-code-validation#19]
It looks like the regex for the Irish post codes (AKA Eircodes) is incorrect 
Please see page page 6 of the product guide (https://www.eircode.ie/docs/default-source/gating-files/ecaf---(eircode-address-file)-product-guide-edition-2-version-2---publishedb6a16c390ba0643fbc0cff00006e1d14.pdf)

I dont feel confident enough to write good regex expressions but gave it a try and I think the following should be correct /[AC-FHKNPRTVWXY]{1}[0-9]{1}[0-9W]{1}[0-9AC-FHKNPRTV-Y]{4}/

Test: https://regex101.com/r/9Jmabs/3

**Comment by axlon** [comment]
Thanks for reaching out,

Let me preface this by saying I don't live in Ireland and have never been, so I'm by no means an expert on their postal codes.

Based on your example I'm gathering that the pattern the package currently ships with is too lenient, however I don't think changing it is a good idea (because I don't want this to negatively affect people currently using this package).

I am working on a new version of this package which will allow for patterns to be overridden, but I do not have an ETA for when that will be released. For now, I think your best bet is probably to fork this package and work from that.

**Comment by taftse** [comment]
I do live in Ireland and was provided the link to the documentation linked above from Eircode the Postcode Management Licence Holder when looking for access to the Eircode Database ( which requires a subscription) to validate Eircode's to addresses 

I don't currently use this library but was advised (by a friend)  that this one was one of the best at validating and as such thought I should let you know that you are actually letting non valid Eircodes through 

Page 3 of the document (linked in my previous comment) list the details on how an Eircode should be validated which is what I used to try and write the proper regex
